image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "export ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder" >> ~/.bashrc
      echo "export ELECTRON_CACHE=$HOME/.cache/electron" >> ~/.bashrc
      echo "export ELECTRON_SKIP_BINARY_DOWNLOAD=1" >> ~/.bashrc